# .goreleaser.yml
# Build customization
builds:
  -
    env:
      - CGO_ENABLED=0
    id: "ledger"
    main: ./ledger/.
    binary: ledger
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
archives:
  -
    builds:
    - ledger
    wrap_in_directory: true
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      freebsd: FreeBSD
      openbsd: OpenBSD
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
