# .goreleaser.yml
# Build customization
builds:
  -
    id: "ledger"
    main: ./ledger/.
    binary: ledger
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - i386
      - arm
      - arm64
archives:
  -
    builds:
    - ledger
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
