# .goreleaser.yml
before:
    hooks:
    - man -Tpdf -l ledger/man/ledger.1 > ledger/man/ledger.1.pdf
    - man -Tpdf -l ledger/man/ledger.5 > ledger/man/ledger.5.pdf
builds:
  -
    env:
      - CGO_ENABLED=0
    id: "ledger"
    main: ./ledger/.
    binary: ledger
    ldflags:
      - -s -w -X github.com/howeyc/ledger/ledger/cmd.version={{.Version}} -X github.com/howeyc/ledger/ledger/cmd.commit={{.Commit}} -X github.com/howeyc/ledger/ledger/cmd.date={{.Date}} -X github.com/howeyc/ledger/ledger/cmd.builtBy=goreleaser
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
archives:
  -
    builds:
    - ledger
    files:
    - man/*
    - LICENSE.txt
    wrap_in_directory: true
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      freebsd: FreeBSD
      openbsd: OpenBSD
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
